"""empty message

Revision ID: 657327dd98c4
Revises: 
Create Date: 2019-11-16 12:29:37.107592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657327dd98c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=True)
    op.create_index(op.f('ix_location_uuid'), 'location', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_uuid'), table_name='location')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
