"""empty message

Revision ID: 763ba7bc84b3
Revises: 657327dd98c4
Create Date: 2019-11-16 16:21:26.349762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763ba7bc84b3'
down_revision = '657327dd98c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criminals',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criminals_uuid'), 'criminals', ['uuid'], unique=True)
    op.create_table('incident_reports',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('what_happened', sa.String(), nullable=True),
    sa.Column('how_it_happend', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('where_it_happend', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_uuid'), 'incident_reports', ['uuid'], unique=True)
    op.create_table('websites',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_uuid'), 'websites', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_uuid'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_incident_reports_uuid'), table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_index(op.f('ix_criminals_uuid'), table_name='criminals')
    op.drop_table('criminals')
    # ### end Alembic commands ###
