"""empty message

Revision ID: 7b2bb908b9ad
Revises: 737d3d9c6024
Create Date: 2019-11-16 17:02:23.496940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2bb908b9ad'
down_revision = '737d3d9c6024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criminal_incident_association',
    sa.Column('criminal', sa.Integer(), nullable=True),
    sa.Column('incident', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criminal'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['incident'], ['incident_reports.id'], )
    )
    op.add_column('incident_reports', sa.Column('criminal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_reports', 'criminal')
    op.drop_table('criminal_incident_association')
    # ### end Alembic commands ###
