"""empty message

Revision ID: 7bce24136b0d
Revises: 7b2bb908b9ad
Create Date: 2019-11-16 17:08:27.556084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bce24136b0d'
down_revision = '7b2bb908b9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_reports', 'criminal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_reports', sa.Column('criminal', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
